spring.application.name=ReactiveMongoDemo
spring.data.mongodb.username=${MONGO_USER}
spring.data.mongodb.password=${MONGO_PASSWORD}
spring.data.mongodb.host=${MONGO_HOST}
spring.data.mongodb.port=${MONGO_PORT}

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

#spring.profiles.active=init